# Generated by Django 4.2.19 on 2025-05-05 12:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlgoPlan',
            fields=[
                ('roster_id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('start_date', models.PositiveSmallIntegerField()),
                ('end_date', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('no_of_consecutive_working_days', models.IntegerField(default=0)),
                ('no_of_consecutive_night_shifts', models.IntegerField(default=0)),
                ('no_of_consecutive_offs', models.IntegerField(default=0)),
                ('worked_last_shift', models.BooleanField(default=False)),
                ('total_no_of_shifts', models.IntegerField(default=0)),
                ('no_of_night_shifts', models.IntegerField(default=0)),
                ('no_of_day_shifts', models.IntegerField(default=0)),
                ('no_of_leaves', models.IntegerField(default=0)),
                ('no_of_working_sundays', models.IntegerField(default=0)),
                ('no_of_working_saturday', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WorkHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_consecutive_working_days', models.IntegerField(default=0)),
                ('no_of_consecutive_night_shifts', models.IntegerField(default=0)),
                ('no_of_consecutive_offs', models.IntegerField(default=0)),
                ('worked_last_shift', models.BooleanField(default=False)),
                ('total_no_of_shifts', models.IntegerField(default=0)),
                ('no_of_night_shifts', models.IntegerField(default=0)),
                ('no_of_day_shifts', models.IntegerField(default=0)),
                ('no_of_leaves', models.IntegerField(default=0)),
                ('no_of_working_sundays', models.IntegerField(default=0)),
                ('no_of_working_saturday', models.IntegerField(default=0)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiftwise_backend_app.doctor')),
                ('roster_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiftwise_backend_app.algoplan')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(max_length=50)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiftwise_backend_app.doctor')),
                ('roster_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiftwise_backend_app.algoplan')),
            ],
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('day_shift_doctors', models.JSONField(default=list)),
                ('night_shift_doctors', models.JSONField(default=list)),
                ('roster_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiftwise_backend_app.algoplan')),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiftwise_backend_app.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='OffRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('off', 'Off'), ('leave', 'Leave')], default='off', max_length=10)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiftwise_backend_app.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Dependents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_start', models.IntegerField()),
                ('dep_end', models.IntegerField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiftwise_backend_app.doctor')),
                ('roster_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiftwise_backend_app.algoplan')),
            ],
        ),
    ]
