# Generated by Django 4.2.19 on 2025-05-06 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shiftwise_backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dependents',
            unique_together={('doctor', 'roster_id')},
        ),
        migrations.AlterUniqueTogether(
            name='offrequest',
            unique_together={('doctor', 'date', 'month', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('doctor', 'roster_id')},
        ),
        migrations.AlterUniqueTogether(
            name='workhistory',
            unique_together={('doctor', 'roster_id')},
        ),
    ]
