# Generated by Django 4.2.16 on 2025-01-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftwise_backend_app', '0003_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='no_of_consecutive_night_shifts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctor',
            name='no_of_consecutive_offs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctor',
            name='no_of_consecutive_working_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctor',
            name='worked_last_shift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offrequest',
            name='type',
            field=models.CharField(choices=[('off', 'Off'), ('leave', 'Leave')], default='off', max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='scheduling_half',
            field=models.IntegerField(default=0),
        ),
    ]
