# Generated by Django 4.2.16 on 2025-01-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftwise_backend_app', '0005_roster'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='role',
            field=models.IntegerField(default=0),
        ),
    ]
