# Generated by Django 4.2.16 on 2025-02-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftwise_backend_app', '0006_doctor_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgoPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('algorithm', models.CharField(choices=[('full', 'Full'), ('half', 'Half')], max_length=4)),
            ],
            options={
                'ordering': ['year', 'month'],
                'unique_together': {('month', 'year', 'algorithm')},
            },
        ),
    ]
