# Generated by Django 4.2.16 on 2025-02-20 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shiftwise_backend_app', '0007_algoplan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='algoplan',
            options={},
        ),
        migrations.CreateModel(
            name='Team_backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(max_length=50)),
                ('scheduling_half', models.IntegerField(default=0)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiftwise_backend_app.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='AlgoPlan_archives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('algorithm', models.CharField(choices=[('full', 'Full'), ('half', 'Half')], max_length=4)),
            ],
            options={
                'unique_together': {('month', 'year', 'algorithm')},
            },
        ),
    ]
