# Generated by Django 4.2.16 on 2025-02-20 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shiftwise_backend_app', '0008_alter_algoplan_options_team_backup_algoplan_archives'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='algoplan',
            unique_together=set(),
        ),
    ]
